# Healthcare App Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app
        image: cloud_project-healthcare-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: healthcare-config
        - secretRef:
            name: healthcare-secrets
        resources:
          requests:
            memory: "16Mi"
            cpu: "5m"
          limits:
            memory: "32Mi"
            cpu: "10m"
---
# Database (Single shared instance)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-db
  template:
    metadata:
      labels:
        app: healthcare-db
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: healthcare-secrets
              key: sa-password
        - name: MSSQL_PID
          value: "Express"
        resources:
          requests:
            memory: "16Mi"
            cpu: "5m"
          limits:
            memory: "32Mi"
            cpu: "10m"
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-pvc
---
# Services Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-management-api
  template:
    metadata:
      labels:
        app: patient-management-api
    spec:
      containers:
      - name: api
        image: cloud_project-patient-management-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: healthcare-config
        - secretRef:
            name: healthcare-secrets
        resources:
          requests:
            memory: "16Mi"
            cpu: "5m"
          limits:
            memory: "32Mi"
            cpu: "10m" 