# Healthcare App Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app
        image: cloud_project-healthcare-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: healthcare-config
        - secretRef:
            name: healthcare-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

# Database (Single shared instance)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-db
  template:
    metadata:
      labels:
        app: healthcare-db
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: healthcare-secrets
              key: sa-password
        - name: MSSQL_PID
          value: "Express"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-pvc

# Patient Management API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-management-api
  template:
    metadata:
      labels:
        app: patient-management-api
    spec:
      containers:
      - name: api
        image: cloud_project-patient-management-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: healthcare-config
        - secretRef:
            name: healthcare-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehr-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehr-api
  template:
    metadata:
      labels:
        app: ehr-api
    spec:
      containers:
      - name: api
        image: cloud_project-ehr-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: healthcare-config
        - secretRef:
            name: healthcare-secrets
        env:
        - name: ConnectionStrings__EHR
          valueFrom:
            configMapKeyRef:
              name: ehr-config
              key: ConnectionStrings__EHR
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

# Appointment Scheduling API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduling-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-scheduling-api
  template:
    metadata:
      labels:
        app: appointment-scheduling-api
    spec:
      containers:
      - name: api
        image: cloud_project-appointment-scheduling-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: healthcare-config
        - secretRef:
            name: healthcare-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"